feat: adding new /decide endpoint
optimizely/agent pull request #292
Opened 2020-12-29 23:51 UTC by pawels-optimizely

## Summary

Adding new endpoint /decide. 
it takes one optional  URL parameter "key" which is a feature key and the body:

```
type DecideBody struct {
	UserID         string                 `json:"userId"`
	UserAttributes map[string]interface{} `json:"userAttributes"`
	DecideOptions  []string               `json:"decideOptions"`
}
```
with DecideOptions values: 
```
"DISABLE_DECISION_EVENT",  "ENABLED_FLAGS_ONLY", "IGNORE_USER_PROFILE_SERVICE",
"EXCLUDE_VARIABLES", "INCLUDE_REASONS"
```
when "key" parameter is not provided then it displays all the available features.

2020-12-30 20:52 UTC, msohailhussain commented on pkg/handlers/decide.go
> +	decideOut := []DecideOut{}
may be rename it to `decideOuts` or array, more understandable.

2020-12-30 20:52 UTC, msohailhussain commented on pkg/handlers/decide.go
> +		decideInner := DecideOut{d, d.Variables.ToMap()}
make it `decideOut`

2020-12-30 20:52 UTC, msohailhussain approved these changes
lgtm

2021-01-06 21:52 UTC, jaeopt requested changes
Looks good.
I see "decideForKeys" support missing. Is it by design?
Suggested to change a test case.

2021-01-06 21:52 UTC, jaeopt commented on pkg/handlers/decide_test.go
> +			Reasons:      []string{},
Aren't we supposed to have "Variables" non-empty here?  If not, can we modify the tests to validate Variables?

2021-01-07 21:40 UTC, msohailhussain commented on api/openapi-spec/openapi.yaml
> +                type: array
Please add appropriate response, what exact object keys will be returned.

2021-01-07 21:41 UTC, msohailhussain commented on api/openapi-spec/openapi.yaml
> +      - $ref: '#/components/parameters/decideKeyParam'
dont' we have any other param?

2021-01-07 21:41 UTC, msohailhussain commented on api/openapi-spec/openapi.yaml
> +            $ref: '#/components/schemas/DecideContext'
again DecideContext?

2021-01-13 08:02 UTC, oakbani requested changes
Looks good overall. Minor changes requested.

2021-01-13 08:02 UTC, oakbani commented on api/openapi-spec/openapi.yaml
> +      requestBody:
nit. move requestbody before responses

2021-01-13 08:02 UTC, oakbani commented on api/openapi-spec/openapi.yaml
> +        userId:
I think you can define all these possible values as enums. so that open spec fails if any other string option is passed within the options

2021-01-14 08:05 UTC, oakbani reviewed
open api spec looks good.

2021-01-14 17:15 UTC, mjc1283 requested changes
LGTM, but let's wait until Go SDK release to merge/release this.

2021-01-14 17:15 UTC, mjc1283 commented on go.mod
> +	github.com/optimizely/go-sdk v1.5.2-0.20201229233509-7c2b19099252
This should not be merged/released until we have a full release (1.5.2) of Go SDK that can be used.

2021-01-14 17:16 UTC, jaeopt approved these changes
LGTM with nits - improve test names

2021-01-19 22:42 UTC, mjc1283 approved these changes

2021-03-01 19:52 UTC, merged