chore: prepare 2.4.0 release
optimizely/agent pull request #300
Opened 2021-03-01 23:21 UTC by Mat001

## Summary
Changelog for 2.4.0 (decide-api) release

2021-03-01 23:22 UTC, Mat001 reviewed
@jaeopt What do you suggest I write instead of the set of new APIs. We only have one new endpoint `/decide`. The rest are APIs based on GO-SDK

2021-03-02 19:32 UTC, jaeopt requested changes
Change go sdk message to be consistent with prev versions

2021-03-02 19:32 UTC, jaeopt commented on CHANGELOG.md
> +Under the hood Agent uses Go SDK which implements Decide APIs. If interested to learn more about them see [Go SDK v1.6.0](https://github.com/optimizely/go-sdk/tree/v1.6.0).
```suggestion
Upgrade to use [Go SDK v1.6.0](https://github.com/optimizely/go-sdk/tree/v1.6.0). This adds support for OptimizelyDecision.
```

2021-03-02 23:45 UTC, Mat001 commented
@msohailhussain Can I ask you also to review pls

2021-03-03 06:07 UTC, yasirfolio3 requested changes
Have suggested some changes, please have a look.

2021-03-03 06:07 UTC, yasirfolio3 commented on go.sum
>  github.com/optimizely/go-sdk v1.6.1-0.20210226222257-68aca7d10f77 h1:YGHuD2FA1qPkRqDSKJwuw5pGQmip8S6hOBcRPcYKntE=
```suggestion
```

2021-03-03 06:07 UTC, yasirfolio3 commented on go.sum
>  github.com/optimizely/go-sdk v1.6.1-0.20210226222257-68aca7d10f77/go.mod h1:1uinGREH+AdijSRw3qitWkvIna1e/ZGN5eymNYPjw1A=
```suggestion
```

2021-03-03 17:25 UTC, Mat001 commented
@jaeopt @yasirfolio3 Can you review/approve?
Your requested changes have been addressed.

2021-03-03 17:27 UTC, yasirfolio3 approved these changes
LGTM

2021-03-03 17:43 UTC, jaeopt approved these changes
LGTM

2021-03-03 17:46 UTC, merged