feat(forced-decision): Adding acceptance tests for forced-decision.
optimizely/agent pull request #325
Opened 2021-11-24 10:35 UTC by yasirfolio3

## Summary
- Adding acceptance tests for forced-decision api.

2021-11-29 20:33 UTC, Mat001 requested changes

2021-11-29 20:33 UTC, Mat001 commented on tests/acceptance/test_acceptance/test_decide.py
> +            }
The use of triple quotes looks a little confusing. Is that the only way? What about single quotes?

2021-11-29 20:33 UTC, Mat001 commented on tests/acceptance/test_acceptance/test_decide.py
> +def test_decide_with_forced_decision__feature(session_obj, flag_key, expected_response, expected_status_code, forced_flag, forced_rule, forced_variation):
What about other forced decision api's? @jaeopt what do you think?

2021-11-29 20:33 UTC, Mat001 commented on tests/acceptance/test_acceptance/test_decide.py
> +def test_decide_with_forced_decision__feature(session_obj, flag_key, expected_response, expected_status_code, forced_flag, forced_rule, forced_variation):
Also, could we have cariation override for forced decisions in /v1/override endpoint? Like here: https://github.com/optimizely/agent/blob/yasir/forced-decision-acceptance/tests/acceptance/test_acceptance/test_overrides.py

2021-11-29 20:33 UTC, Mat001 commented on tests/acceptance/test_acceptance/test_decide.py
> +        resp.raise_for_status()
add a new empty line

2021-11-29 22:45 UTC, jaeopt approved these changes
LGTM

2021-11-30 20:08 UTC, Mat001 approved these changes

2021-11-30 23:39 UTC, Mat001 commented on tests/acceptance/test_acceptance/test_decide.py
> +              "ruleKey": "{}".format(forced_rule),
@msohailhussain @yasirfolio3 Feel free to merge. String formatting would be nice to update, other than that lgtm.

2021-12-01 17:33 UTC, merged