(chore) Prepare for 2.7.0 release
optimizely/agent pull request #336
Opened 2022-03-28 09:18 UTC by yasirfolio3

## Summary
- Update changelog for a new minor release 2.7.0 - UserProfileService

## Issues
- https://optimizely.atlassian.net/browse/OASIS-8254

2022-03-29 00:04 UTC, jaeopt approved these changes
LGTM

2022-03-29 00:25 UTC, Mat001 requested changes

2022-03-29 00:25 UTC, Mat001 commented on CHANGELOG.md
> +- Added `UserProfileService` support. Out of the box implementations include `in-memory`, `rest` and `redis`. In-memory service supports both `fifo` and `lifo` orders. ([#326](https://github.com/opti
Change "Added" to "Add" (also below).
And change "Updated" to "Update" (below).

We've been using directive verbs, not past tense. To be consistent how verbs have been used.

2022-03-29 17:45 UTC, Mat001 approved these changes
LGTM

2022-04-05 22:00 UTC, jaeopt approved these changes
LGTM with a nit

2022-04-05 22:19 UTC, merged