[FSSDK-9111] chore: prepare for 4.0.0-beta release
optimizely/agent pull request #387
Opened 2023-05-08 17:31 UTC by pulak-opti

## Summary
- Prepare for 4.0.0-beta release

## Ticket
- [FSSDK-9111](https://jira.sso.episerver.net/browse/FSSDK-9111)

2023-05-08 18:01 UTC, yasirfolio3 requested changes

2023-05-08 18:01 UTC, yasirfolio3 commented on CHANGELOG.md
> +
This should be updated to reflect the new odp functionality that we're releasing similar to all of our other sdk's. [https://github.com/optimizely/go-sdk/pull/373/files](url). Also we might have to fix acceptance tests before releasing this

2023-05-09 16:48 UTC, Mat001 requested changes

2023-05-09 16:48 UTC, Mat001 commented on CHANGELOG.md
> +* [Send Optimizely Data Platform data using Advanced Audience Targeting](https://docs.developers.optimizely.com/feature-experimentation/v1.0/docs/send-odp-data-using-advanced-audience-targeting-go)
I think I would remove this reference from go-sdk. 

Instead I would add ref about server side sdk-s plus pages specific for Agent:
[Server SDK Support](https://docs.developers.optimizely.com/feature-experimentation/v1.0/docs/advanced-audience-targeting-for-server-side-sdks)

[Use Optimizely Agent](https://docs.developers.optimizely.com/feature-experimentation/docs/use-optimizely-agent)
[Configure Optimizely Agent](https://docs.developers.optimizely.com/feature-experimentation/docs/configure-optimizely-agent)
@yasirfolio3 What do you think.

2023-05-09 16:48 UTC, Mat001 commented on CHANGELOG.md
> +
Would also add this mention of breaking change:
![image](https://github.com/optimizely/agent/assets/1386553/5c4edd4c-58a5-46e8-b817-c402769ff8aa)
@yasirfolio3 what u think?

2023-05-09 18:41 UTC, Mat001 approved these changes
looks ok to me now

2023-05-09 21:51 UTC, yasirfolio3 approved these changes
LGTM

2023-05-09 22:06 UTC, Mat001 commented
@pulak-opti Before we release, let's fix the sourceclear issue

2023-05-11 15:36 UTC, merged